apiVersion: v1
kind: Secret
metadata:
    name: minio-backup-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:7IYiZnx7hMeSJl7oPDYOg1sbS+Y=,iv:zarnIAUQRA9yXTM84DTSG/q5FnOkFKzbpcLBvxg68mY=,tag:3zPLJcwQPJ4SeLqGFCeIAA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CpoWRpcwSnVy7QtzDpxQ5Q463aOlCWyH+2hZ5BqAi29gvD7fWeQPxQ==,iv:L6UxHvIZsT19U+WiH/zEb/1nzDVG5VeKQEvP8V13WDc=,tag:thgtub54zFhB3AYlZrhSaw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:ZS1C77wCm/aH+A7J/LElGlpRAB716bre1ehay6c=,iv:LXAC+D/aMoRygaW93IGLFpHZou7Eu5UdIQHZF4q5Wrk=,tag:tML6MRL5QzR2ZMK87balHA==,type:str]
    VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:Xbb/DHk=,iv:rqFJ/NaWlmEZLeG2sJqjzdCHvcwNk8w42dYL+bIl5Tc=,tag:dic/5KkFixhOZ13koP+h6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OUhZemVmNU9FaVNPdXlB
            cnBrZWVCTFJJYklXRDVtS0JvdnN4Y3RxRzM0CmVpT054RGNKRnBrZFd1T2JBSldk
            R3k3dm1ldmJBZ1JQSGRsTDNBVFJ6NkUKLS0tIHhwdFB4TisrZ3cxaE5sbkJ3Vmg0
            WGtxNFd3RVRtQXBGOHdWZENSUXNoWUkKOftD9IH8BgnBxd86IewcWEyED0WG3owd
            dnExmN9fp4pfHx7svhVJDNHv8EXPFWg9AA4DUCacj3S61POoYd0R0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vh8zt4kg9j9acsx3jwxqz3yyssg25qtx7u0chaymjpr6k2vzq39szc4y5a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T09:16:47Z"
    mac: ENC[AES256_GCM,data:xf6U3FUgSGF3DGvRGHFK+pd9TugwnR+5PIcL4UXvFHMGQLyQ3TG5jvJDeh/k31DFq/cwjHn+Np3etJUtbNqwUbB+GjtkX0nPkjuP/9CWCP2vH4QPKGW4iLZG01N3jxVajuYHyTX3vnMUW1lYe0w0Op6Z78/9Gg9xQyymtHNRyvY=,iv:brxiqbSWJv+aYb4cSzSWje7F3a9CcZtZd/hrRP7rmzk=,tag:qAn67Atw4wpsvOoywXNmiQ==,type:str]
    version: 3.13.3
