apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: lldap-system
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:fURZpNCZBuQiQI7MInnCe4RGcvQfKD4yWWekqEtvQgWKHe+o2z2t1ERZL4eW+ZPk3yB9be93qQQMtFw7+bIztA==,iv:fAtyaRuQ7DoTMoHScxP74rOjDh9Y7yyO8+g8uhR06Vw=,tag:u5YCVk6+rrgN25KgniRn1w==,type:str]
    key-seed: ENC[AES256_GCM,data:dFg4ito6Z8ID8rt+j/WFY97SjsElRRCh+7bEbnUEeqOD03dkBLYcjWcJYutC/jATmAlV8cp418n6hn6tZAH9/Q==,iv:ar+0lNmqVhG1CQjZwAysff3iRmfloTmi/p9Tx8piScU=,tag:HJlL8Jkg+ODoKDk9vjNJyA==,type:str]
    admin-password: ENC[AES256_GCM,data:pPF/s/go5S6FRKJ0x6Q6CfnrnFk=,iv:cJ+Lyl3iIpw/Lsq5EHNy97R38V0sMur13VFNGHstTPI=,tag:0TyGkeRJPo+HltqHcLw3KQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSGhYZjBtS3pVd1Z6L29T
            N25JMnR1cEw4SUtER1NZb1dSQjhyQk5oQm1zCnllMUw4MEx3Q2hlRm5ibm54Wjlu
            NlZYUnBKSUROY0U4ZlNnTHpFYStVWWsKLS0tIFpXdEVoUEIrMTBFdTRYSzFkZVVC
            WE5mbmJWeUtrbWJCL2tKSDc5QVJlOWcK5GeRwXJlQ4I2tVjMLWXH+Cv6uQzpD5PU
            ja+4HFeujlOHU9TPEHpjeD4oQmNQHmPQRXXS+I+kRqF2wVIDbHw89w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vh8zt4kg9j9acsx3jwxqz3yyssg25qtx7u0chaymjpr6k2vzq39szc4y5a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T19:37:01Z"
    mac: ENC[AES256_GCM,data:TUGU1DEoO6/Amj+EbV60pN0eRv4rTSSbZ7KyqGGW5iae2Qq9jYpU42oJ3iILvt8MMDmxBePiN0c2G8QTgccxhjzybhj1QxCBOLnmVs5AkJUJ61VQvp2ihc8U7cO4VrDsLgXe5L2/NUmEyZR7o8BHlFAf6F6UYvCT8Yhge6Fc5yE=,iv:aaLSbT4mM2BfRhKr4+rI+/OdXC3B9aNokHIGOSBUUNo=,tag:e2d1Go5pVAMWu189GjQ7MQ==,type:str]
    version: 3.13.3
