---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  namespace: authelia-system
data:
  users_database.yml: |
    users:
      admin:
        disabled: false
        displayname: "Admin"
        password: "$argon2id$v=19$m=65536,t=3,p=4$q3d8YvT6qR/K6xU8$1+qA7C/X"
        email: admin@smb-111.azby.fr
        groups:
          - admins
