---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia-release
  namespace: authelia-system
spec:
  chart:
    spec:
      chart: authelia
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: authelia-system
      version: 0.11.22
  interval: 1m0s
  values:
    secret:
      existingSecret: authelia-secret
    configMap:
      theme: dark
      default_redirection_url: https://auth.smb-111.azby.fr
      server:
        port: 9091
      log:
        level: info
      authentication_backend:
        file:
          path: /config/users_database.yml
          password:
            algorithm: argon2
      session:
        cookies:
          - domain: smb-111.azby.fr
            default_redirection_url: https://auth.smb-111.azby.fr
      storage:
        local:
          path: /config/db.sqlite3
      notifier:
        filesystem:
          filename: /config/notification.txt
