---
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "s3://smb-111@us-east-1/"
  credentialSecret: "minio-backup-secret"
  pollInterval: "5m0s"
