apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: authelia-system
type: Opaque
stringData:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:GR7t1xajh1RAPvAbW5R0VixTaq+R2tu6oy+nC69fwAPGKOukYkDmvM06RhzfQS6x/RD6docg3PRDLCbsDzZnGQ==,iv:qP623qAsNtiRZpxE/DyjpepT9z0ZYAPOrraKgaGolEU=,tag:fLUTSYTv78xoRLwsLJHZ1w==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:FrBThCxYVFvzNqPR5sfsH6QHP5uF5n4C2HZ9jaTuMb2Cs5CE9YAZC9JLEfNaQ3No+u3Tu0xU1t23FhoHnVcF4w==,iv:Ydpu9yhIaCer0hgqEzKMVfVgfOE0GQkXGnLwT7giuW4=,tag:3XMx3NuXHQu2bjv73RaAsQ==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:jMRKOipiMDQ1IbB5nTAnZxOT4u0M1sNVD0fIhniUDqjrGtFKbl+08wdcLPE1qLlRZuNb29XeXoEyMuiqPd06XQ==,iv:MV2/Hpc6ACKo9XwYlKAe7zPwLVFBouYvDUce5OukVcY=,tag:leSxoYHckILtdaDF0bkwlA==,type:str]
    authentication.ldap.password.txt: ENC[AES256_GCM,data:oUQkiZOKkSU=,iv:mJx9m4TkS+nETO0HjNpfevzyf2yC7x8jgn18po9Bk6M=,tag:xG+Tq1uCIoqU08i0GIU96g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYL3NkNThHVDVUWlpabDBr
            MGV6QkEyd0dKeit2alZGM095OEZzNm1laUZRCmVyVVQ3SjRBamdjUU83d0xuTmNF
            cVo0OWROWmpxNEF0NDBwMFNhRFFIRlkKLS0tIHd1VkhzZ3NEeEpHODNISTJOeWtp
            OUpCZStxMjJmMUtPZTBaMWVIK0VnUW8Kq08K0zcP5r4W785oVIERUrMEGtMYKWsA
            muhRFE4QyKaRGgcbyH8FUIW7Yklf36c8nDBbuLbIBmxmJsq54cJKhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vh8zt4kg9j9acsx3jwxqz3yyssg25qtx7u0chaymjpr6k2vzq39szc4y5a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T16:51:46Z"
    mac: ENC[AES256_GCM,data:jAo8qhbYolidowe687FzsCL+rZ/G9wKpebHxwgwPVMebKLmqaUobz/vS09eBbNxCeuj23CAb6lDkw5yVY/W2MOP1uynoJZhy/GAUcxHm1MKpUAjHWXzM/Cykfo/jLxu7JiXwawXlFYx1IOeUPGrBG7yLVg9utyV6imqIT8PZZUM=,iv:568pnuiNmaKFLjuzLf1dImW5tLnOtvFHEdJKYHWCkvQ=,tag:NvWinXm5hbBMvGk0DYsyyw==,type:str]
    version: 3.13.3
