---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale-system
spec:
  timeout: 1m0s
  install:
    remediation:
      retries: -1
  releaseName: tailscale-operator
  chart:
    spec:
      chart: tailscale-operator
      version: '1.x.x'          # à épingler après le premier déploiement
      sourceRef:
        kind: HelmRepository
        name: tailscale-repo
        namespace: tailscale-system
      interval: 12h
  upgrade:
    remediation:
      retries: 3
  values:
    operatorConfig:
      hostname: smb-111-operator

