apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring-system
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:MGSep6w=,iv:yq89SjqU2pgOx3CjqORcQZ9ypMIjGTn8wY1VL+F7POQ=,tag:1rb2YTnFCKoVY5S64kzIow==,type:str]
    admin-password: ENC[AES256_GCM,data:F9f72yQDYIivP38LGttlwHSrgXc4WiRqjZD67+HSa4c=,iv:57w+C9tE7hcwmv7YYykyuMlywDiO9YygTt3RRyupJZU=,tag:UYm/e8YDHw4Uwsxx9cy2TA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOWFuUFlMWHJBNWRNVEhW
            YWZ1djFvYzRYUzRjcy9yYWdlSEYzTWVQaUVNCk5aUmw2cEh0dlNCOWVNWGQ2anBT
            c0x6bHRoZzlrTlVFWWZ0cWhPZlordE0KLS0tIElBR2FyVWNacEZYeWcxc0M5b0Rt
            MWpVeGtJZmNDYjNHWksrTFpWdUdNTEUKZwavBZFuJ8S/QRFFB4dZ5MvYhOjx3Kxi
            lPqLmjNyr6+T0FeaaRyDEH/YMQqPcWYDUWoZtKSGTNhlHompAmrXFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vh8zt4kg9j9acsx3jwxqz3yyssg25qtx7u0chaymjpr6k2vzq39szc4y5a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T17:21:39Z"
    mac: ENC[AES256_GCM,data:jdq4x1cPZxkDko+/J1zq3sRiUJC67V5xnoJDxK115XftZpryNQOfYxyePcS5vwa4nNqYNF7A9ADW3RF4r9mnQPlyAMR6hmiKSBWzLjVbrLqez192Kqb77mFAxJufOJw8u0ZbJ7HZI/PmSgwwqz8NseBgWFInN2UiCE1CkFd8/Nk=,iv:HpvKolGKnM2JgFrW0+3YqXRG8Tv6xKBey56xIfguIn4=,tag:3EIjkFBv+hxDzrT+4Fv3SQ==,type:str]
    version: 3.13.3
