---
- name: Adapter l'IP du master dans le kubeconfig local
  ansible.builtin.replace:
    path: "{{ local_kubeconfig }}"
    regexp: 'https://127\.0\.0\.1:6443'
    replace: "https://{{ vip_ip }}:6443"

- name: Ajuster les permissions du fichier kubeconfig
  ansible.builtin.file:
    path: "{{ local_kubeconfig }}"
    mode: '0600'

- name: Vérifier la présence de k9s sur la machine locale
  ansible.builtin.command: which k9s
  register: k9s_check
  failed_when: false
  changed_when: false

- name: Installer k9s en local si nécessaire
  ansible.builtin.unarchive:
    src: "{{ kubeconfig_local_k9s_url }}"
    dest: "{{ kubeconfig_local_k9s_dest }}/"
    remote_src: yes
    extra_opts:
      - --include=k9s
    creates: "{{ kubeconfig_local_k9s_dest }}/k9s"
  become: yes
  when: k9s_check.rc != 0

- name: Vérifier la présence de kubelogin
  ansible.builtin.command: which kubectl-oidc_login
  register: kubelogin_check
  failed_when: false
  changed_when: false

- name: Installer kubelogin (plugin kubectl oidc-login)
  ansible.builtin.unarchive:
    src: "{{ kubeconfig_local_kubelogin_url }}"
    dest: /usr/local/bin/
    remote_src: yes
    include:
      - kubelogin
    creates: /usr/local/bin/kubelogin
  become: yes
  when: kubelogin_check.rc != 0

- name: Exposer kubelogin comme plugin kubectl
  ansible.builtin.file:
    src: /usr/local/bin/kubelogin
    dest: /usr/local/bin/kubectl-oidc_login
    state: link
  become: yes
  when: kubelogin_check.rc != 0

- name: Générer le kubeconfig OIDC
  ansible.builtin.template:
    src: kubeconfig-oidc.yaml.j2
    dest: "{{ kubeconfig_local_oidc_kubeconfig }}"
    mode: '0600'
  vars:
    kubeconfig_local_ca: "{{ (lookup('file', local_kubeconfig) | from_yaml).clusters[0].cluster['certificate-authority-data'] }}"

