apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: lldap-system
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:aSTAE1sqp50PtAsV3tT05eskMndYmgq9AmetkqRnCZX4Xcn19GhRiQ9fHqFLzMRsLTcal26DckSpS3M/YUZ9rQ==,iv:RXcrSNkOPM1fjzbFQJDNS8WNTvb1GJRLOttohqMdwF8=,tag:GEAcUoUw77+S6tmVcANJmg==,type:str]
    key-seed: ENC[AES256_GCM,data:p4aHsjdLk5MTIdtxdqzm7iH2JFOcCK+5wdZV/rF8su7zLi7RoAnKOn8iRjw9cVljMbgSUFbx8j2ZFDvQwSgq5Q==,iv:u1jsZkswVLqiGeqA15Gi4W05DYup8PgBsoRhnjGcv+0=,tag:lfpQt5yzcSrBU16WbCbyaw==,type:str]
    admin-password: ENC[AES256_GCM,data:jLjidMo=,iv:aJ73Ptajvi6j9d4PHS6+wk0m3Ox65UY6itPShmf0xTQ=,tag:ZsuG4geR3jj3i/NThS8AGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dEZscDVXMENhdFJjUjc0
            YUN2bE53bGVLaHhHMjVWZkQ4YUNCZEdBSUc0CjYwQVlyZFJNSTBJWlVCL0RhNkhF
            dno0OENkVlFSSjBxS0VYcHVLWnNtbWcKLS0tIGdIbk1Yd3pscXF2SUVnSkl5ZmdU
            Z0t1ZkVmRXFEVUF6MWlncTl6RE9LWUUKZLTK0jec76z5embpwyPTLC6fNTeCuIq2
            lq5PcjYR/nJEWGOeaiWviV5Tn2qh8WXHUVf8FbFMp3tJc1emk02ncg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vh8zt4kg9j9acsx3jwxqz3yyssg25qtx7u0chaymjpr6k2vzq39szc4y5a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T19:29:16Z"
    mac: ENC[AES256_GCM,data:orvjsAAEh5h3Vk4Ebz6UzmlhMXizoqMOoPFVWZ/Yzk7C7kqjCLgbnJLmLF2Xx1UR2uIeArkW8pYVrrO5pcU95ITe3a2FfhutU5Jb6k4hZWJE8Aff6921HLC2MIariooFhHTttQ2x9BnkOO3urPPmBzJ+CfWNUW41n5qhF0v1sAc=,iv:QTUdvszWBKYlsFSderEbp3flxixh4ZXBAc6r0En73Gw=,tag:stHq/JkS6p9WUVDhtZr6ng==,type:str]
    version: 3.13.3
