#ENC[AES256_GCM,data:DSd7DI7vlvx2oF262M5xn+R/JStEwxVxqw==,iv:w8byfyu10noS9RlBzPdEHFt5qqQPQIglCjMcSQyUwA8=,tag:DbyvNrqcZWpXdMQ/VlY5IA==,type:comment]
github_token: ENC[AES256_GCM,data:EWBZMmp53q5NCQ6+Cepm63SJF80Wnf3m7YWQfEECtajE8yFJkZ1I4Q==,iv:i2f3kRzOX+NoCEpqr3Qa606TKOI7gR3LePrPP1EQQJo=,tag:7rUxCSFJA3xViUnOL0VnQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMVYyNFpDVE9rMVpscTBu
            K1htWXlsMVR4WlNLZzVMMEJPRithUVhUSW00CnVzZ0dMbG03OVNzY3N2a0lEcjEr
            eWZWWUY0ZTNSM2Y5NTBTbzVMWVdqVHcKLS0tIG04UXYwQnRlVDV2RFU0a1F0SStP
            TlNSUTZScnRXMUsrVkptNy93LzF2Q0UKQze9X+qK086wc3U8epfRHHxmlalnz6/+
            LuRgPNG7l/ccaw0GgHZAfxQJKgWHl7neOKOf94OugnELsbGOJrn0yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vh8zt4kg9j9acsx3jwxqz3yyssg25qtx7u0chaymjpr6k2vzq39szc4y5a
    lastmodified: "2026-09-25T16:10:25Z"
    mac: ENC[AES256_GCM,data:KFLasfNyGOH1v6/J55u5xZbI8TWYfRbaftyM8pRBovBwC85ftAR2yH2VNedDnt6w5ahlIF9SLaXoWOZcmxbaNuWoioxcuYOQzeaUALGaLgeBapf2ULHNgr1bOzgETOSrjYb4cAwH60cb4Tvi9WPiC/+IGITN9dERynjeQDId78g=,iv:QRaAClvMcp0dawhfl1JJH6vxxQShM6GYzPOWH0lKFcc=,tag:vjaGyENR+Ab+5Ibrowdf7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
