apiVersion: v1
kind: Secret
metadata:
    name: minio-backup-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:RoI2g/GupTBUXv11Z4/XTf6HrUY=,iv:ZFNlFxc2vPX7v/6FsqRgmq4Znf6czGlwYqwJg1hrk+8=,tag:yWHoGe6zgj1+IAIEApJpCg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wjq8axD08NgDMYedrbNrQ+VXjwkyLU+kDTOkFMR0NyOHi2ZLyQBnUg==,iv:IvAtC4rUUkDbP2DQxRLVe4IXyXp6JK7boC8XMjfKB8w=,tag:VIfGyzDG5ZDo1T8jFJ+Dbw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:qMqoMzlNLChtsHf8k27qf/5Y08VJ1B0+Ag==,iv:LO80JMtcCc+1yno9+jLEsiDXNwiot+bw8btFYuqoNwY=,tag:iN3ARWJOFMNa/9dMBaB8XQ==,type:str]
    VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:5NvwTV8=,iv:U7qgSJ7KQuRWPdUIYeNrr3lBJr43Gi8w1swuRo5SuJ8=,tag:4HNyewQHjCl7T2RBF2xH2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS1d5SERodUVidHNDejg0
            K0pLMStPbERWQmZFa3VBNUFZQjlXRUZqWmo4CnJ3VElyc3N3cWpYemN3TGFSM0ti
            QUgxamcxRHlyRHlWSGVkaDFoa3FsQm8KLS0tIEozZGRtYTNmaGlLdUNzSjBwUW5p
            b051L1AvcGExVWUycDVGdWhXM0FldEUKe72NYLxVfHH30AOq+38XErt+GXB0xL1l
            fF1ZJTjEEuc2smihVNqbMTislweeZUJ9MZy3ugIYYcYJkfQbqM1psw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vh8zt4kg9j9acsx3jwxqz3yyssg25qtx7u0chaymjpr6k2vzq39szc4y5a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T10:18:55Z"
    mac: ENC[AES256_GCM,data:8w3ULqvT4yQ16pL74NUORsBSHEvU52BwBl2TQwqntZlsMddtBr5UoHunfbsmI9q9bYtfNMH4J+EXRYhcAAnbJjRk7LpPQpAd1xAgaiwQvVq193QXZXN/OPGz5S71CXicaSKwW0xxPsgqGNqCmp858Ehr6zSGCZkxJRiO91W+Yw4=,iv:B6ys8wrwPU8EeeoBlktJuDDg41ZSTFqxROkULUPX8Og=,tag:FoI/DZvC1BH93+zxi6pScw==,type:str]
    version: 3.13.3
