apiVersion: v1
kind: Secret
metadata:
    name: minio-backup-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:D5DaWBwzUoiF/PnGxLeWxMqlKPI=,iv:OTrYOeGaPHS7Nx6f9qWrkv0JzeWDHaQvD9xgWhL2+tg=,tag:kszziW9TkpiB33JFgFCRhA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Qr9BWfJt4BOQWxoZ3D00pmZnLzWQFBuQsvcpPWmBdHoqSOA09fd7qQ==,iv:2GcGSIjXi2a7sPcuSsXsPeGtjoM8aHO+cCJXtENxCgg=,tag:PgpVRWlrRmsLP/yhP2fMAQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:zdHgjgxxyxiJAdJXnzdScGu94aUkNlySTQ==,iv:Zy6i+f6UhXJAlz8Msib8LxPa2xopJScBZZ84IIKiUp8=,tag:GICVuH04H1Sta7qi9S54iw==,type:str]
    VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:EFvxZgw=,iv:7hszbEt6+GrP+Tgm+IbayQE/Iv5AlmW+Qvn6gxJ579M=,tag:qyPZihtF951uoIQhlW9Lsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUG9sbkRiQ09OWTlMMDY1
            UGIxM2ZhRTFNdUY5TTljMzIzTnZ2Mk84WGhFCkt6Zy9wQjA5MG5VTlNZN0RuT2J4
            ZFJsaXpNbDlvL0l2K005S3h2MWdLU1EKLS0tIDdzMG5xQjZ2NHU4QzVjcWlvbVM5
            NGdzY3JNS1l4bmU0aHBHazFkYnhnSkkKzbcEcQYjJmai3e3nfDagYPC/8wAA5YtG
            Uf0ucTlh48cZkTDyr699hDV1EN8/suzf/bJA7oUlqD0InIpkqkpOIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vh8zt4kg9j9acsx3jwxqz3yyssg25qtx7u0chaymjpr6k2vzq39szc4y5a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T08:32:59Z"
    mac: ENC[AES256_GCM,data:BW9U8Pio+/JDthREK2JoXljuSppnDMn7COqonWtrIxIhWtqVQ7iiVdBXn+HNVeHjNRupIl38Uiv972WxwgxSmvin0ycL+nujrC3MqDrAfr/VwyGnxl6q3VCKZLmu160Iz7YFSsYdS+Vq8CT1Xw/HRysEoUBpCZgPKTAvCmeqyp8=,iv:YRQU6BQTySTFI4V++g+qJqxkEIwhD9pw20XwVKFuUQ4=,tag:zEotodGcgYHGfl5sHY1xDw==,type:str]
    version: 3.13.3
