apiVersion: v1
kind: Secret
metadata:
    name: minio-backup-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+F4tuBNMaovshlPcwQcNSXNq2Fw=,iv:g8YZs7c+hKupheDOfc5Gmh8LMeErDezv5HdnNf7VHBY=,tag:c56VzwBmwsb02fq4s9j/xw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PW9YrdOWjFigcWNVO3Jps8Zao83HJICQRiTP609CFNgz4v+y0BdEaw==,iv:vbxkPCF3oj5v9dgC/rwH7K/J7HPRAajZVKJ8D+Y81os=,tag:vKvNkD56f0/4wrgp3tfzcg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:oANEi9GJDlgRkusQRCPgpQ2LYVYKSRHdH48zNrc=,iv:7/uFXHcBka3y0oi6B8h1Kwp7LiRdsJaoPAzdv637HyA=,tag:iHK0o29e0JnOLIg4fWcA9Q==,type:str]
    VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:TIamnvU=,iv:zhrJOWPhj5eeQYO2YW/wwXkHB5dpSgeUIvr2WtycAvg=,tag:QVgYTpl8a33msdOSzt70Pg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWThVM3kwUko2c1phakFi
            K3pFK1JCd0VHbERKVHViWGpEZHJDQm1sOUZnCld3SHR6MzVqNU82QXl5V1U1R3k1
            UkNiSHJxMnlreVA2QWdXZHA3Y2hHY2MKLS0tIFNoTjR5elQ4ZDNydEJrRWg4a2tI
            bFVSNExKWkZSZUdVbHVjQnRJNDZ6QmsK1x4XUUJLs0JT07ucCfxkFD9kOUY0PMCP
            oNuBH6eIIp+DHjALSYeitsm/66Wr4Xn2/VrhehXUBv2L7oW9lnhZxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vh8zt4kg9j9acsx3jwxqz3yyssg25qtx7u0chaymjpr6k2vzq39szc4y5a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T15:37:43Z"
    mac: ENC[AES256_GCM,data:pftpJWd4wO2e7ie1rCJ4bhirq+p4ryxw1mTQoIZ22sInj2mByjRF2y15YAoVDLK45EgMwZ/wLNDRdAehBBjPxsY55+rbiCZSfPZsa622+jX91/YxOHYQuYg0eqgwa8SMpud60zIqfbFb4cWEBl/EZ9BCFearJ6enr0ind5fWpJo=,iv:lVM3BlLJieZDg+DxDBdZUN3z9ZTjA1EgWfaw5s284yI=,tag:wFNgXKJ0uAUyxrgIExAUXQ==,type:str]
    version: 3.13.3
