---
- name: Préparation de toutes les machines
  hosts: k3s_cluster
  become: yes
  roles:
    - role: common
      tags: [common]

- name: Nœuds maîtres (control plane HA)
  hosts: masters
  become: yes
  serial: 1
  roles:
    - role: k3s_server
      tags: [k3s_server]
    - role: kube_vip
      tags: [kube_vip]

- name: Nœuds workers
  hosts: workers
  become: yes
  roles:
    - role: k3s_agent
      tags: [k3s_agent]

- name: Post-installation et récupération du kubeconfig
  hosts: masters[0]
  become: yes
  roles:
    - role: k3s_postinstall
      tags: [k3s_postinstall]

- name: Configuration locale
  hosts: localhost
  connection: local
  become: no
  roles:
    - role: kubeconfig_local
      tags: [kubeconfig_local]

- name: FluxCD
  hosts: masters[0]
  become: yes
  roles:
    - role: flux_bootstrap
      tags: [flux]

