apiVersion: v1
kind: Secret
metadata:
    name: ovh-credentials
    namespace: cert-manager-system
type: Opaque
stringData:
    applicationKey: ENC[AES256_GCM,data:ovRD6gwEB0Wzdw1tqH7www==,iv:ovQi7vcDOIo05jphkKJT4j69ugvwMVTdg/zC8gNybXY=,tag:lZPyWEAfsiyF4iF77zRzRg==,type:str]
    applicationSecret: ENC[AES256_GCM,data:xavENkvTRMe7X0ZVQETWXgUvr2OEytjWBXPAMzLWBuM=,iv:Mrx37GsmaUQ2aQ6K6x6DqeAGww8/VVHbWNG49ob4uqA=,tag:k3As0wFGTWOmn64YvQ8GCA==,type:str]
    consumerKey: ENC[AES256_GCM,data:EulKhWjcuiSSH3gcypyAsAER5pllVPeGZ0/8ETQYZa4=,iv:hOixSNefL/HL0SKb7aqQ3Be/fEZIywuysKQudxujHt8=,tag:8sz3yhe2DLVzXZlchz4ZtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcXAyRUxFTExHTTZ0YzMr
            cC85ZmNNWVh1aGpYZDdSQmRVZW00QzhxSWd3CjU4RENnNnJMTWNWeU1SOWxHWXU5
            MURoWWpsM09rN2dMQytjZ2dleGdQbGsKLS0tIENPajZYaWZsNVlNUlV6dktGSHpJ
            emVnTzhNMXg4cTFLSjZNL3MwWDNubFUKDuf3DyEGN3FSYZE1k4aYmLNfbREDkbgr
            I4+VjIupM3XdzP7/zv8jNNRXgH3GIAwHdX8TDb3H68s5DpSrzzCOGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vh8zt4kg9j9acsx3jwxqz3yyssg25qtx7u0chaymjpr6k2vzq39szc4y5a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T16:47:07Z"
    mac: ENC[AES256_GCM,data:6Qt0hbKFRs8MBgXaNpzrCROGU6lV6/abAa1KBvEptrLnKZeWO9VHCMBLtBzxnZOVPn+RrmZGJkZxFr+wiH2SfmpNq8boTsvyMj4E/ZIOaht0/zRbg++RA/9JD+Lvbp6GhZRkOs8zU2fO8F8oaTUHWpO0cKTuPoxxVVLHzbWCv5g=,iv:3tZgB555p15tLcYy8Gl/P43v+6ANOXRNZAMb0LecgoY=,tag:dmOOt14oTkhWquLfagPpWg==,type:str]
    version: 3.13.3
